# Generated by Django 5.1.3 on 2024-11-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NBA",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("rating", models.IntegerField(default=0)),
                ("jersey", models.CharField(max_length=10)),
                ("team", models.CharField(max_length=100)),
                ("position", models.CharField(max_length=10)),
                ("b_day", models.CharField(max_length=15)),
                ("height", models.CharField(max_length=15)),
                ("weight", models.CharField(max_length=15)),
                ("salary", models.IntegerField(default=0)),
                ("country", models.CharField(max_length=100)),
                ("draft_year", models.IntegerField(default=0)),
                ("draft_round", models.IntegerField(default=0)),
                ("draft_peak", models.IntegerField(default=0)),
                ("college", models.CharField(max_length=100)),
                ("version", models.CharField(max_length=10)),
            ],
        ),
    ]
