# Generated by Django 5.1.3 on 2024-11-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uploadFile", "0002_alter_nba_salary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nba",
            name="weight",
            field=models.CharField(max_length=100),
        ),
    ]
