# Generated by Django 5.1.3 on 2024-11-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uploadFile", "0003_alter_nba_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nba",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
