# Generated by Django 5.1.3 on 2024-11-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uploadFile", "0005_alter_nba_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nba",
            name="draft_peak",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="nba",
            name="draft_round",
            field=models.CharField(max_length=20),
        ),
    ]
