# Generated by Django 5.1.3 on 2024-11-30 02:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uploadFile", "0006_alter_nba_draft_peak_alter_nba_draft_round"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nba",
            name="draft_year",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="nba",
            name="rating",
            field=models.IntegerField(),
        ),
    ]
