# Generated by Django 5.1.3 on 2024-11-30 02:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uploadFile", "0007_alter_nba_draft_year_alter_nba_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nba",
            name="b_day",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="nba",
            name="college",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="nba",
            name="country",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="nba",
            name="draft_peak",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="nba",
            name="draft_round",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="nba",
            name="draft_year",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="nba",
            name="full_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="nba",
            name="height",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="nba",
            name="jersey",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="nba",
            name="position",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="nba",
            name="rating",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="nba",
            name="salary",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="nba",
            name="team",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="nba",
            name="version",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="nba",
            name="weight",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
